// src/components/Navbar.vue
<template>
  <nav class="navbar" aria-label="main navigation">
    <div class="navbar-brand">
      <router-link class="navbar-item" to="/">
        <img :src="favicon" alt="Husky Corner"/>
      </router-link>
      <router-link class="navbar-item" to="/">
        Husky Corner
      </router-link>
      <router-link class="navbar-item" to="/convert">
        Convert to Excel
      </router-link>
    </div>
  </nav>
</template>

<script>
import favicon from "../assets/img/favicon.png";

export default {
  data: function() {
    return {
      favicon
    };
  }
};
</script>

// src/components/Navbar.tsx
import React from "react";
import { Link } from "react-router-dom";

import Favicon from "./icon.png";

class Navbar extends React.Component {
  render() {
    return (
      <nav className="navbar">
        <div className="navbar-brand">
          <Link className="navbar-item" to="/">
            <img alt="Husky Corner" src={Favicon} />
          </Link>
        </div>
        <Link className="navbar-item" to="/">
          Husky Corner
        </Link>
        <Link className="navbar-item" to="/convert/">
          Convert to Excel
        </Link>
      </nav>
    );
  }
}

export default Navbar;
